apiVersion: gh-infra/v1
kind: File
# metadata:
#   owner: <YOUR_OWNER>
#   name: <YOUR_REPO>

spec:
  files:
    # .github/infra
    - path: .github/infra/patches/.gitkeep
      source: github://naa0yama/boilerplate-rust/.github/infra/patches/.gitkeep

    - path: .github/infra/File.yaml
      source: github://naa0yama/boilerplate-rust/.github/infra/templates/File.yaml
    - path: .github/infra/Repository.yaml
      source: github://naa0yama/boilerplate-rust/.github/infra/templates/Repository.yaml

  via: pull_request
  commit_message: "ci: sync managed files"
  pr_title: "chore: sync files"
  pr_body: |
    ## Summary
    Automated file sync.
